Fix index out of bound when resetting TracingInspector (#115)
Fixes out of bound error when using `fuse()` in `TracingInspector`.

Error before:
```
index out of bounds: the len is 0 but the index is 0
panicked at src/tracing/arena.rs:54:31:
```

Cause: `CallTraceArena` is initialized using `default()` but when
calling `clear()` the default root node is removed.

---------

Co-authored-by: Matthias Seitz <matthias.seitz@outlook.de>